version: "3"

services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_NAME=bootcamp2
      - DB_USER=user
      - DB_PASS=password
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=bootcamp2
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data

volumes:
  postgres_vol:
    driver: local